name: build
on: push
jobs:
  compile:
    name: Compile project
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install VCVars
        shell: pwsh
        run: Install-Module -Name VCVars -Force
      - name: Compile
        shell: pwsh
        run: |
          pushvc (invoke-vcvars -TargetArch x86 -HostArch AMD64)
          cmake --preset x86-msvc-relwithdebinfo -D3DMM_PACKAGE_WIX=OFF
          cmake --build build/x86-msvc-relwithdebinfo --target dist
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: 3D-Movie-Maker
          path: build/x86-msvc-relwithdebinfo
